### PR TITLE
FAT32 file read fix

### PR DESCRIPTION
**Pull request by valentinbreiz**

### CODE REVIEW

**Review by quajak — APPROVED** [review]

**Comment by quajak** [comment]
Are the tests passing locally?

**Comment by valentinbreiz** [comment]
I didn't try to Write large files only Read I need more debug to merge this

**Comment by quajak** [comment]
Ok

**Comment by valentinbreiz** [comment]
I commented the read all bytes tests due to appveyor time limitation. But it's working locally

image

**Comment by valentinbreiz** [comment]
Close this for https://github.com/CosmosOS/Cosmos/pull/2783
I don't delete the branch to keep the existing tests I made for a migration to Github Actions

**Pull request closed without merging**
