### PR TITLE
Revert Misha's commit for GCImpl

### PR DESCRIPTION
**Pull request by RaphMar2021**
The commit made by Misha 2 weeks ago broke the 'Cosmos.Core.Memory.Heap.Collect()' function. This commit aims to revert these changes

### CODE REVIEW

**Comment by valentinbreiz** [comment]
What did it broke? It seems to work for me

**Comment by RaphMar2021** [comment]
Heap.Collect

**Comment by RaphMar2021** [comment]
When i tried Mirage with the latest commit, it froze on the setup screen.

**Comment by GoldenretriverYT** [comment]
Yeah there are some issues with Heap.Collect on the latest commit, but were you able to actually verify that it was that commit? Just because it changed the GC code doesn't meant it has to be that commit, so please make sure it was actually this commit.

**Comment by RaphMar2021** [comment]
I reverted back the GCimpl code on my local version, and it works again

**Comment by ADev531** [comment]
it, works for me and i can use gui os over than 10 minutes

**Comment by 9xbt** [comment]
don't blame misha, it's just that the gc is shit but i mean if you optimize your os which i really did with mango it will run just fine, no fps drop

**Comment by RaphMar2021** [comment]
> don't blame misha, it's just that the gc is shit but i mean if you optimize your os which i really did with mango it will run just fine, no fps drop

I didn't blame Misha, they are doing really good work, but Heap.Collect now crashes the OS

**Comment by RaphMar2021** [comment]
I mean, everyone can break everything

**Comment by quajak** [comment]
We might need to readd some code like the original one to prevent the heap from being on top of kernel code. But I think we removed this code to fix https://github.com/CosmosOS/Cosmos/issues/2546. Therefore, we should try find a solution which fixes both issues, rather than just reintroduce the old one

**Comment by pleasenoban** [comment]
i dont think this stops it from overriding the acpi tables though?

**Pull request closed without merging**
