### PR TITLE
Fixing a patch

### PR DESCRIPTION
**Pull request by PratyushKing**
There was a recent commit by @valentinbreiz, that commit changed the copy paths of IL2CPU artifacts from Debug to Release which is not working as of right now on any current linux device and this pull request will revert it back to when it worked, This makes sure that there are no errors during the general build process.

### CODE REVIEW

**Comment by 9xbt** [comment]
I would discard any changes to any `.lock.json` file before making the PR and I would also add an option to switch between debug and release instead of undoing the changes to a coredev

**Comment by PratyushKing** [comment]
> I would discard any changes to any `.lock.json` file before making the PR and I would also add an option to switch between debug and release instead of undoing the changes to a coredev

Well, I wasn't sure about it either so I have enabled to allow edits according to coredevs so its entirely modifyable

**Comment by Kiirx** [comment]
Already done in #2944 
I will finish this when I have time in the week

**Comment by Kiirx** [comment]
consider this PR useless

**Comment by Kiirx** [comment]
and also we don't use Debug but Release so it's even more useless

**Comment by zarlo** [comment]
okay this is some thing that keeps breaking i thing we should just set the out put paths just to be done with it

**Comment by PratyushKing** [comment]
> consider this PR useless also you should continue your minecraft gameplay it was so interesting and also the python tutorial damn your voice makes me wanna eat spicy strawberries

there was no voice.....

**Comment by PratyushKing** [comment]
also yeah ill just keep it closed until theres something fixed, i anyways just update my own repo for changes and use fork

**Pull request closed without merging**
