### PR TITLE
Add compiler optimizations

### PR DESCRIPTION
**Pull request by MEMESCOEP**
I've added the ability to enable compiler optimizations and choose optimization level for a slight increase in performance (Around 3 fps for me).

### CODE REVIEW

**Comment by terminal-cs** [comment]
i wonder if this will make any major differences for other code, as it can vary

**Comment by MEMESCOEP** [comment]
Currently working on making this optional (via a check box in the properties menu)

**Comment by MEMESCOEP** [comment]
@terminal-cs It might, and @quajak suggested that I make it optional (which is a good idea)

**Review by quajak — COMMENTED** [review]
I think you accidently added a few incorrect files to the PR. Could you please remove them?

The actual changes look good although I think we can simplify the UI a bit and remove the boolean flag for `UseCompilerOptimizations` since we can just include 0 as a valid optimization level. Thanks for the work!

**Review by quajak — CHANGES_REQUESTED** [review]
Pressed the wrong button, please see my previous comment for the review.

**Comment by MEMESCOEP** [comment]
Alright, I'll change the code

**Comment by MEMESCOEP** [comment]
gonna close this pr and make a new one because I can't figure out how to remove some of the files that I accidentally added

**Pull request closed without merging**
