### PR TITLE
Cosmos on linux, improved better as per a request

### PR DESCRIPTION
**Pull request by PratyushKing**
As per a requet from @pleasenoban, I have made it such that the debug enabled is only disabled on a specific new template called `csharp-linux`, and yes I have also updated the docs for linux users who want to install the templates. If anyone has further queries please do tell.

### CODE REVIEW

**Comment by valentinbreiz** [comment]
Shouldn't we just disable by default instead of adding the same code?

**Comment by PratyushKing** [comment]
> Shouldn't we just disable debugging by default instead of adding the same code?

I did it but @pleasenoban saw that on windows it somehow made it worse so I did this. Don't worry I tested it in both OS

**Comment by valentinbreiz** [comment]
> > Shouldn't we just disable debugging by default instead of adding the same code?
> 
> I did it but @pleasenoban saw that on windows it somehow made it worse so I did this. Don't worry I tested it in both OS

what do you think @quajak?

**Comment by quajak** [comment]
> I did it but @pleasenoban saw that on windows it somehow made it worse so I did this. Don't worry I tested it in both OS

How is it worse? I think it's better if we disable it by default

**Comment by Jspa2** [comment]
Adding a separate template for Linux is overcomplicating things. I think debugging should be switched off by default for all platforms.

**Comment by valentinbreiz** [comment]
Agree

**Pull request closed without merging**
