### PR TITLE
Verify length when constructing a string

### LINKED ISSUE #2717: Making a string with a negative length should just cause an exception
#### Area of Cosmos - What area of Cosmos are we dealing with?
System.String

#### Expected Behaviour - What do you think that should happen?
`new string(' ', -1);` should just throw `System.ArgumentOutOfRangeException`

#### Actual Behaviour - What unexpectedly happens?
Causes a CPU Exception

#### Reproduction - How did you get this error to appear?
`new string(' ', -1);`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest devkit

### PR DESCRIPTION
**Pull request by jvyden**
Closes #2717

### CODE REVIEW

**Comment by zarlo** [comment]
when length is 0 
we should return String.Empty
like it is in .net https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/String.cs

**Comment by quajak** [comment]
> when length is 0

does this have any actual difference execution wise? "" will be replaced by loading the same constant string each time

**Review by quajak — APPROVED** [review]
Thank you for the fix!

Will wait for Zarlo to get back to me before merging

**Comment by zarlo** [comment]
> > when length is 0
> 
> does this have any actual difference execution wise? "" will be replaced by loading the same constant string each time

nope it will just use more memory

**Comment by jvyden** [comment]
Agreed, but I'm not quite sure how to implement this. We don't return strings directly like it's done in mscorlib.

**Comment by quajak** [comment]
I don't think it actually does because we load a constant string, which does not actually use memory on the heap.

**Pull request merged**
