### PR TITLE
Add Dockerfile so MacOS users can build

### PR DESCRIPTION
**Pull request by abjdev**
This pull request solves issues with building Cosmos Projects using MacOS/Arch Linux
User needs to have Docker installed.

### CODE REVIEW

**Comment by abjdev** [comment]
To Create the container:
```bash
docker container create -i -t --name cosmosos cosmos
```

To build: 
```bash
# Copy project files from host to Container
docker cp . cosmosos:/Cosmos/Osname

docker exec -it cosmosos cd Projects/Osname
docker exec -it cosmosos dotnet build Projects/Osname/Osname.sln
```

Replace `Osname` with your OS name

**Comment by zarlo** [comment]
would you be willing to change this to a Dev Container setup?

**Comment by abjdev** [comment]
> would you be willing to change this to a Dev Container setup?

@zarlo I don't know

**Comment by zarlo** [comment]
> > would you be willing to change this to a Dev Container setup?
> 
> @zarlo I don't know

as in you dont know how to or if you want to. either way is fine

**Comment by abjdev** [comment]
> > > would you be willing to change this to a Dev Container setup?
> > 
> > 
> > @zarlo I don't know
> 
> as in you dont know how to or if you want to. either way is fine

@zarlo okay. can you review it?

**Pull request merged**
