### PR TITLE
Allows user to change install directory

### PR DESCRIPTION
**Pull request by quajak**
If the user is not admin, this allows the user to change the install place to his user's appdata. This fixes the problem I had.

### CODE REVIEW

**Comment by quajak** [comment]
Can afterwards the branch installer-fix be merged with the master?

**Comment by Arawn-Davies** [comment]
Probably via a PR on the CosmosOS/Cosmos repo from this branch to master :)
no issues, errors or unexpected results with this change? along with different deployment options? e.g. PXE, USB (not sure which ones are working atm however)

**Comment by jp2masa** [comment]
This change will allow the user to select a custom path. There's a message pointing that the user should choose AppData\Roaming, so I think it's an acceptable solution for now.

**Comment by fanoI** [comment]
This patch seems OK for me,  @quajak can you "move" it to the Master branch?

**Pull request merged**
