### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by DevBadger10**
I found a minor typo :/

### CODE REVIEW

**Comment by DevBadger10** [comment]
>  [ 68747470733a2f2f6d656469612e74656e6f722e636f6d2f377058497a62386632725541414141642f6d696e6f722d7370656c6c696e672d6d697374616b652e676966 ](https://camo.githubusercontent.com/6dbedc9afd329899bee4d09a34977cba47468eab20dc0e3611edf0d0dbdf1071/68747470733a2f2f6d656469612e74656e6f722e636f6d2f377058497a62386632725541414141642f6d696e6f722d7370656c6c696e672d6d697374616b652e676966) [ ](https://camo.githubusercontent.com/6dbedc9afd329899bee4d09a34977cba47468eab20dc0e3611edf0d0dbdf1071/68747470733a2f2f6d656469612e74656e6f722e636f6d2f377058497a62386632725541414141642f6d696e6f722d7370656c6c696e672d6d697374616b652e676966)

https://media.tenor.com/WWwgfRFI1DwAAAAM/super-sonic-sonic-adventure.gif

**Comment by DevBadger10** [comment]
> 

Lol what is going on in my quotes and gif insertion

**Comment by RaphMar2021** [comment]
msm

**Review by MishaTy — APPROVED** [review]

**Pull request merged**
