### PR TITLE
Serial communication related changes

### PR DESCRIPTION
**Pull request by 9xbt**
Made it possible to change the baud rate of a serial port when enabled and moved COM ports to an enum.

### CODE REVIEW

**Comment by 9xbt** [comment]
Crap why does it fail all the time

**Comment by zarlo** [comment]
Constant value '384' cannot be converted to a 'byte'  source\Cosmos.HAL2\BaudRate.cs
Line: 63
Column: 23
Cosmos.HAL2

**Comment by 9xbt** [comment]
Yes i know i figured that out a while ago

**Comment by 9xbt** [comment]
It should be fixed now

**Pull request closed without merging**
