### PR TITLE
more nuget

### PR DESCRIPTION
**Pull request by zarlo**
work for #2608 

this will be a breaking change we may want to make a userkit after this

### CODE REVIEW

**Comment by zarlo** [comment]
will need someone to update the windows installer

**Comment by zarlo** [comment]
okay can confirm this works on windows

**Comment by quajak** [comment]
> this will be a breaking change we may want to make a userkit after this

Do users have to update existing projects to use nuget?

**Comment by zarlo** [comment]
> > this will be a breaking change we may want to make a userkit after this
> 
> Do users have to update existing projects to use nuget?

yes they will need to add the nuget package ```cosmos.plugs```

**Comment by quajak** [comment]
Can you update the documentation somewhere to reflect that?

**Comment by zarlo** [comment]
yep ill add a breaking change log to the articles and add a link to it in the wiki and read me

**Comment by quajak** [comment]
Thanks, could you please fix the spelling and capitalisation in the text?

**Comment by zarlo** [comment]
okay i think its all fixed, if there are others they will need to be pointed out

**Review by quajak — APPROVED** [review]

**Pull request merged**
