### PR TITLE
Misspeled

### PR DESCRIPTION
**Pull request by lukaandjelkovic**

### CODE REVIEW

**Comment by mterwoord** [comment]
Can you update this pr?

**Comment by lukaandjelkovic** [comment]
@mterwoord what do you mean?

**Comment by ARMmaster17** [comment]
`git checkout <your_branch>`

`git rebase <master_branch>`

`git commit`

`git push`

**Comment by mterwoord** [comment]
Currently I can't merge the PR, because it needs updating.

**Pull request closed without merging**
