### PR TITLE
Guess demo improvements

### PR DESCRIPTION
**Pull request by jp2masa**
## Changes
- Fixed `Random` plug.
- Guess demo generates a random number and can be played more than once.

### CODE REVIEW

**Comment by KingLuigi4932** [comment]
Did you test it?
And shouldn't GenerateGlobalSeed in the System.Private.CoreLib Random?

**Comment by jp2masa** [comment]
Yes, I tested it.

**Comment by fanoI** [comment]
It is not easy probably to make TestRunner test Random(), maybe one could do these tests:

1. Get a Random number in a range
2. Verify that the generated number is in the selected Range
3. Get another Random number in the same range
4. Verify that is NOT the same number of the first Random

**Comment by jp2masa** [comment]
That would cause random test failures.

**Comment by fanoI** [comment]
You fear that 2 subsequent Random numbers could have the same value?

**Comment by jp2masa** [comment]
It's possible, and tests should be deterministic. We can test generating a random number and checking if it's in the given range, which would at least prevent compiler bugs and missing plugs.

**Comment by fanoI** [comment]
OK if tests are added I'd say this could be merged.

**Pull request merged**
