### PR TITLE
Add more options for global init

### PR DESCRIPTION
**Pull request by MEMESCOEP**
I've added the following options to `HAL2.Global.Init`:
* InitSerial
* InitPCI
* InitACPI
* Init AHCI
<br/>
This gives more control to the developer because they can enable/disable certain drivers and initialization steps, which may be helpful when certain drivers/devices/features aren't needed, or the developer is writing their own.

### CODE REVIEW

**Comment by MishaProductions** [comment]
I think that the better approach would be to move everything from Global.Init to the project template.

**Comment by MEMESCOEP** [comment]
> I think that the better approach would be to move everything from Global.Init to the project template.

That could work, but then we'd have a bunch of checkboxes everywhere. Unless we find a different way of course

**Comment by MEMESCOEP** [comment]
> I meant to move it to Kernel.BeforeRun()

Oh alright

**Comment by quajak** [comment]
I think the idea is that we provide a initialise function, which anyone can then implement themselves if they want to change it. Rather than using this flag based approach.

**Comment by MEMESCOEP** [comment]
> I think the idea is that we provide a initialise function, which anyone can then implement themselves if they want to change it. Rather than using this flag based approach.

how would we implement this though?

**Comment by quajak** [comment]
> how would we implement this though? Maybe a function that can be overridden?

Yeah, that is what I was thinking

**Comment by Kiirx** [comment]
PS/2 driver, ac97 (dont really remember the name)... you get the point

**Comment by Kiirx** [comment]
Or we can make it a List and then use foreach to execute all of them (so the type would be Action) https://learn.microsoft.com/en-us/dotnet/api/system.action?view=net-7.0

**Comment by zarlo** [comment]
> Would be better like that but please add so that we can do this with every part of cosmos, even the **vga screen** so that we can really just initialise what is only needed for the user

that can already be done you can override the virtual method in your Kernel (OnBoot, Start or GetTextScreen in the case of vga screen) or you can make a plug to override what cosmos does

**Comment by Kiirx** [comment]
Well then ok we can close the pr then

**Comment by quajak** [comment]
> that can already be done you can override the virtual method in your Kernel (OnBoot, Start or GetTextScreen in the case of vga screen) or you can make a plug to override what cosmos does

Then is there any reason to add more configuration options?

**Pull request closed without merging**
