### PR TITLE
Added a Power class containing a WORKING reboot function

### PR DESCRIPTION
**Pull request by zdimension**

### CODE REVIEW

**Comment by zdimension** [comment]
Done.

**Comment by mterwoord** [comment]
I think interrupts need to be disabled?

**Comment by zdimension** [comment]
Well, it works perfectly without disabling interrupts...

**Comment by mterwoord** [comment]
OK, but then if it somehow doesn't reboot, the OS will just continue running (reacting to interrupts). Can you change this?

**Pull request merged**
