### PR TITLE
implement ramdisk and refactor

### PR DESCRIPTION
**Pull request by AsertCreator**
why it doesn't work? so i made this rAmDisK thing, but it just crashes.

### CODE REVIEW

**Comment by terminal-cs** [comment]
> why it doesn't work? so i made this rAmDisK thing, but it just crashes.

i assume this is for tar files?

**Comment by AsertCreator** [comment]
no, this is just for ramdisk, but it is possible to read tar files and convert them into ramdisks

**Comment by quajak** [comment]
Where does it crash?

**Comment by AsertCreator** [comment]
it crashes when i create new ramdisk

**Comment by AsertCreator** [comment]
and for some reason test is not starting

**Comment by AsertCreator** [comment]
oh there is actually syntx error :P

**Comment by AsertCreator** [comment]
ok, i think this is more user feature and developers should implement that themselves. im changing concept of pr and going to implement ustar filesystem

**Pull request closed without merging**
