### PR TITLE
Updated index.md

### PR DESCRIPTION
**Pull request by zdimension**

### CODE REVIEW

**Comment by mterwoord** [comment]
- Please reorder the directory headlines.. 
- Typo: "Adds support for the Cosmos Kernel project tipe" (tipe -> type)
For the rest, it looks ok.

**Comment by mterwoord** [comment]
Any luck finding the complete version yet?

**Comment by zdimension** [comment]
Can you merge the pull request, only for the index.md file ?

**Comment by mterwoord** [comment]
I think I can. Will do a bit later.

**Pull request merged**
