### PR TITLE
with some more changes

### PR DESCRIPTION
**Pull request by PratyushKing**

### CODE REVIEW

**Review by AsertCreator — CHANGES_REQUESTED** [review]
it's a very bad idea to remove documentation and comments. they're made to help developing cosmos, not to remove them one day.

**Comment by PratyushKing** [comment]
I am adding back comments

**Comment by PratyushKing** [comment]
added back comments for RAT

**Comment by 9xbt** [comment]
@zarlo we should close this, how the fuck is removing the comments gonna make the gc significantly faster as @GoldenretriverYT said :sob:

**Comment by ptobuon** [comment]
> it's a very bad idea to remove documentation and comments. they're made to help developing cosmos, not to remove them one day.

I agree, and removing documentation will not improve performance.

**Comment by PratyushKing** [comment]
> > it's a very bad idea to remove documentation and comments. they're made to help developing cosmos, not to remove them one day.
> 
> I agree, and removing documentation will not improve performance.

i have readded

**Comment by Guillermo-Santos** [comment]
> > > it's a very bad idea to remove documentation and comments. they're made to help developing cosmos, not to remove them one day.
> > 
> > 
> > I agree, and removing documentation will not improve performance.
> 
> i have readded

Yes, but not all of it, there are a lot of it that is still removed, and even so, what @GoldenretriverYT said, removing comments do not improve performance...

**Comment by quajak** [comment]
Please readd the other removed comments, I think they all helped make the code more clear

**Comment by EliaSulimanov** [comment]
I don't see what this change is about.
And also - if you made a change, and want to undo it, you should not just copy the old content from another branch and commit it as your owns, as it breaks the history of changes.

If there is no change, there should be no commit on the line. Removed and readded content will add your name as a contributor to a line, but there is actually no contribution made.

I vote closing this PR.

**Pull request closed without merging**
