### PR TITLE
#143 has been finished ui for the test runner is finished

### PR DESCRIPTION
**Pull request by Geramy**
I have finished making the test runner ui hope you like it! :)

### CODE REVIEW

**Comment by mterwoord** [comment]
Well, We're getting there..

- I'd like to not see all messages by default (See the difference between the OutputHandlerConsole and OutputHandlerFullConsole). After a click, you'd see the full details
- Make some kind of counter where it lists how many succeeded and how many didn't.
- Somehow make the list autoscroll, so you see the last message without problem.

**Comment by Geramy** [comment]
Okay next ill do a log level selection, then I will add a counter and make
it auto scroll! :)

**Comment by mterwoord** [comment]
Also, if you close the window, it should just stop running, instead of continuing..

**Comment by mterwoord** [comment]
And bonus points if you could add the same kind of nesting the console does. Please try to put more context visible in general (like the run configurations,etc)

**Comment by Geramy** [comment]
Okay so nest by level and yah I just have ro exit the thread in close

**Pull request merged**
