### PR TITLE
Added EqualityComparer Plug + Change In Plug Resolution

### PR DESCRIPTION
**Pull request by Seeker1437**
This Pull Request accomplished the following

1: Added DictionaryTests
2. Changed plug resolution in regards to resolving generic types

### CODE REVIEW

**Comment by mterwoord** [comment]
Even though this PR has been open for 1.5 months now, it certainly is not forgotten! We did parts of the PR during other work already, so we will be likely (manually) grabbing parts of the PR. Hope you don't mind. 

Thanks!

**Comment by Seeker1437** [comment]
Hehe no issues here, let me know if you want me to just close it or leave it as is :)

**Comment by fanoI** [comment]
@Seeker1437 a question this will make Dictionary usable on Cosmos?

**Comment by charlesbetros** [comment]
Completed in a separate branch. Merged to master.

**Pull request closed without merging**
