### PR TITLE
Update Install-VS2015.bat

### PR DESCRIPTION
**Pull request by nithinswarrier**
Deleted del command to stop error file not found and set %ProgramFiles% if Windows is 32bit for msbuild directory

### CODE REVIEW

**Comment by mterwoord** [comment]
The delete command is intentional: It makes sure an old version is not getting installed.

I'm pretty sure there's something else going wrong. Are you on 32-bit windows?

**Comment by nithinswarrier** [comment]
Yes, I'm using Windows 10 32 bit. I think there is no need for del command as msbuild replaces files present in the directory.

**Comment by mterwoord** [comment]
MSBuild doesn't remove the old version if it didnt succeed, which is what the del command is for. 

Someone could fix it though by making things work both on 32-bit and 64-bit windows.....

**Comment by nithinswarrier** [comment]
Yes it works on 64 and 32 bit if msbuild is installed

**Comment by charlesbetros** [comment]
Why not use something like
```reg.exe query "HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0" /v MSBuildToolsPath```

**Comment by mterwoord** [comment]
@nithinswarrier So if you change how MSBuild.exe is found, it works, even with the delete command?

**Comment by mterwoord** [comment]
@nithinswarrier Can you verify with latest master? I think we got this fixed now.

**Comment by mterwoord** [comment]
This is merged now.

**Pull request closed without merging**
