### PR TITLE
[WIP] Canvas framework renewal

### PR DESCRIPTION
**Pull request by terminal-cs**
This is a draft pr that will be worked on my me and discussed about with the maintainers

- [x] Remove pen class
- [ ] Make base canvas class useable as drawing surface (mostly finished)
- [x] Make base canvas class use memcpy functions for fast drawing
- [ ] make extention drivers as simple as possible to prevent any slowdowns
- [ ] Remove unnessacerry duplcate functions in driver and canvas classes (kinda done)

### CODE REVIEW

**Comment by terminal-cs** [comment]
This is not finished and many things are incomplete

**Comment by AsertCreator** [comment]
finally! i got sick of my canvas using all the system memory and making it laggy

**Comment by terminal-cs** [comment]
i don't got time for this so it is on hold for a little while

**Comment by terminal-cs** [comment]
I am closing this for now as i have taken on too much of a chalenge and it would be too much work for me to do alone

**Pull request closed without merging**
