### PR TITLE
Update Cosmos.iss

### PR DESCRIPTION
**Pull request by BioShot**

### CODE REVIEW

**Comment by quajak** [comment]
Is it possible to do the check for if apps are running without using `WBEMScripting.SWBEMLocator`?

**Comment by BioShot** [comment]
I'm not sure. I'm not good at Visual Basic or inno setup, but from my knowledge no. Do you thing you could make my updated code into the actual cosmos exe, because I just get more build errors.

**Comment by quajak** [comment]
What build errors are you getting?

**Comment by BioShot** [comment]
That all the objects in https://github.com/CosmosOS/Cosmos/blob/master/Setup/Cosmos.iss#L142 do not exist.

**Comment by quajak** [comment]
Could you please post the error log?

**Comment by BioShot** [comment]
mhm i'll leave a link to a video give me a sec

**Comment by BioShot** [comment]
here:
https://tinyurl.com/cosmoserror

**Comment by quajak** [comment]
The thing you encountered in the .iss file with the {} is expected, since that value is passed from the builder. Can you confirm that running install-vs2019.bat also leads to an error?

**Comment by BioShot** [comment]
Yes, Can you compile that code into the exe so i can use cosmos? Sorry for the request. I have anther error. I'll show that to.
Do you also have notifications on this? Because its longer for a response.

**Comment by BioShot** [comment]
https://bit.ly/3FfPNsG

**Comment by quajak** [comment]
Your current issue with running the devkit installer is definitely that you deinstalled nuget. Can you reinstall nuget and try again? Your issue building is most likely a combination of not having cosmos installed and the project not being a cosmos project. Both of these can be fixed, once you have either the user or the devkit installed.

We appreciate everyone who wants to contribute. Please look at the cross platform pull requests for current work on make scripts. To contribute just open a pull request with the changes and we will review them.

**Comment by BioShot** [comment]
Ok, will do.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by BioShot** [comment]
Ok, how do I reinstall negut im working on a project that used nuget. And no problem, I like helping people.

**Comment by BioShot** [comment]
I have a video hold on for just a sec

**Comment by BioShot** [comment]
https://download1497.mediafire.com/lza3hnz175ug/8ttmlnfga4ot33z/2022-05-04+15-01-15.mp4

**Comment by quajak** [comment]
Can you please post the log output from the build processes as a text in a pastebin?

**Comment by BioShot** [comment]
sure, but how?

**Comment by BioShot** [comment]
oh wait sure.

**Comment by BioShot** [comment]
https://pastebin.com/0Wr00TMB

**Comment by quajak** [comment]
Can you please open the Build.sln and see if you can build it manually?

**Comment by BioShot** [comment]
already tried

**Comment by quajak** [comment]
Whats the result?
Can you please post the build logs from inside vs.

**Comment by BioShot** [comment]
sure. Will, it says you have to attach a script to all of them then require it.

**Comment by BioShot** [comment]
why can't you just publish this and get the fixed exe. Won't that work?

**Comment by Arawn-Davies** [comment]
If we fixed all programming issues simply by removing code blocks or commenting out lines, there wouldn't be any code at all.

**Comment by BioShot** [comment]
I know, Can't you just try.

**Pull request closed without merging**
