### PR TITLE
remove gen1 files

### PR DESCRIPTION
**Pull request by AsertCreator**
if you dont want, the best solution will be to separate them into another branch. btw, i doubt i removed every gen1 file
p.s. i have really bad short-term memory or what?
in addition to these changes, i updated cosmos.common readme to be markdown. plus i refactored kernel.cs file

### CODE REVIEW

**Comment by zarlo** [comment]
the files you removed are apart of gen3

**Comment by AsertCreator** [comment]
genius. closing for a moment

**Comment by AsertCreator** [comment]
i doubt they are. they havent been updated in 5 years

**Comment by AsertCreator** [comment]
when gen2 appeared?

**Comment by AsertCreator** [comment]
oh, they really are. ok, i will find another ones when i get to pc

**Pull request closed without merging**
