### PR TITLE
might make console faster

### PR DESCRIPTION
**Pull request by zarlo**

### CODE REVIEW

**Comment by valentinbreiz** [comment]
@zarlo why this will be faster ?

**Comment by zarlo** [comment]
UpdateCursor(); gets called alot less

**Comment by mterwoord** [comment]
Can you:
- rename iWriteChar to something like InternalWriteChar or something like that
- Have WriteChar use InternalWriteChar

**Comment by zarlo** [comment]
will fix the RP when i have the time

**Comment by fanoI** [comment]
A doubt but Console.Write/WriteLine with for example 'è' it is working? I think that the conversion from UFT-16 to CP437 should be done in Write(Char)... what do you think?

**Comment by jp2masa** [comment]
Yes, the conversion should be moved to InternalWriteChar.

**Pull request merged**
