### PR TITLE
Improve Math.Sqrt() implementation.

### PR DESCRIPTION
**Pull request by invisal**
Using Newton Method and a good square root approximation to improve the Math.Sqrt() speed.

### CODE REVIEW

**Comment by fanoI** [comment]
Thanks for you contribution!

To test double "equality" I've created an utility method when I tested Double:
https://github.com/CosmosOS/Cosmos/blob/master/Tests/Cosmos.Compiler.Tests.Bcl/System/DoubleTest.cs#L12

probably this could be put in some common static utility class in the BCL test sources...

**Comment by invisal** [comment]
I have added the all the edge cases.

**Comment by fanoI** [comment]
OK can you use DoublesAreEqual() moving it in a static class (something as EqualityHelper... in other tests there is an ArrayAreEqual() too if I remember well)?

**Comment by invisal** [comment]
Okay. I will try. Right now, I am struggling to run the TestRunner. It always show "error: symbol `DebugStub_SendStackOverflowOccurred' undefined" error message. I will move once I solve the TestRunner first ^^

**Comment by fanoI** [comment]
Ah so you ever executed TestRunner in your machine then?

**Comment by fanoI** [comment]
Minor thing but here should say "Newton" no "Network":

https://github.com/invisal/Cosmos/blob/0cee95b9480b807144bb73383e661428c310150f/source/Cosmos.System_Plugs/System/MathImpl.cs#L412

**Comment by fanoI** [comment]
Thank you for you contribution!

**Pull request merged**
