### PR TITLE
Add UEFI toggle to project properties

### PR DESCRIPTION
**Pull request by MEMESCOEP**
Users can choose if they want to compile their OS with UEFI support.

### CODE REVIEW

**Review by quajak — APPROVED** [review]
Thank you for the contribution!

**Comment by 9xbt** [comment]
Would it actually work? If it would it would be awesome

**Comment by MEMESCOEP** [comment]
@9xbt I've tested it and it seems to work quite well

**Comment by 9xbt** [comment]
> @9xbt I've tested it and it seems to work quite well

Hmm does VGA text mode work? i dont think that does

**Comment by MEMESCOEP** [comment]
> > @9xbt I've tested it and it seems to work quite well
> 
> Hmm does VGA text mode work? i dont think that does

All my commit does is apply Misha's UEFI changes if the checkbox is checked. If it isn't, it's essentially the same thing as compiling a project before that PR was merged

**Comment by 9xbt** [comment]
Ahhh okay

**Comment by 9xbt** [comment]
> If it doesn't work, then I've got some work to do

I thought it wouldn't work but i guess it should

**Pull request merged**
