### PR TITLE
Implement MBR creating and partition information adding

### PR DESCRIPTION
**Pull request by husaral2**
Partition tables and new partitions can be created now.

### CODE REVIEW

**Review by quajak — CHANGES_REQUESTED** [review]
Thank you the the PR!

Would it possible to add some tests to the test runner (for example [Diskmanager tests](https://github.com/CosmosOS/Cosmos/blob/master/Tests/Kernels/Cosmos.Kernel.Tests.DiskManager/Kernel.cs) to ensure that the code works as expected?
Additionally, it would be great if you could add a small section to the documentation to explain to other users when and how to use the functions.

**Comment by husaral2** [comment]
Added the docstrings, made the changes and changed the test kernel to create MBR and write partition information at first when the disk starts to format the disk.

**Review by quajak — DISMISSED** [review]
Thanks for the changes!

**Comment by quajak** [comment]
Looks like its causing the DiskManager tests to fail. Have you been able to reproduce it locally?

**Comment by husaral2** [comment]
> Looks like its causing the DiskManager tests to fail. Have you been able to reproduce it locally?

It was because I tried to access the partition after I recreated the partition table. It should work now.

**Review by quajak — APPROVED** [review]

**Pull request merged**
