### PR TITLE
Update PCSpeaker.cs

### PR DESCRIPTION
**Pull request by zarlo**

### CODE REVIEW

**Review by quajak — DISMISSED** [review]

**Comment by zarlo** [comment]
just need someone to merge it

**Comment by MishaTY** [comment]
Cannot merge due to build failing

**Comment by zarlo** [comment]
typo fixed

**Review by MishaTY — APPROVED** [review]

**Comment by quajak** [comment]
It seems like the current code doesnt compile for AppVeyor.

**Review by quajak — APPROVED** [review]

**Pull request merged**
