### PR TITLE
Fixed the TestRunner file in docs

### PR DESCRIPTION
**Pull request by lukaandjelkovic**

### CODE REVIEW

**Comment by mterwoord** [comment]
No. you first have to merge in cosmos master, then update this PR with the cmmits you need to do, then I can merge it...

**Comment by charlesbetros** [comment]
This code is submitted under #255 also? We could close this one and take the changes from #255.

**Comment by charlesbetros** [comment]
There is a merge conflict. Can you update it sonic can merge?

**Comment by lukaandjelkovic** [comment]
i dont know how to edit the pull request #255.

**Comment by charlesbetros** [comment]
Duplicate

**Pull request closed without merging**
