### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by zarlo**
this should let you set the branch from command line

### CODE REVIEW

**Comment by zarlo** [comment]
@MishaTY  when ever you are free

**Comment by Kiirx** [comment]
imma try

**Comment by Kiirx** [comment]
hey I didnt knew there was a crossplatform branch too for Common

**Comment by Kiirx** [comment]
Error when adding the Cosmos.core_asm nuget package on project
```Unable to find package Cosmos.IL2CPU. No packages exist with this id in source(s): Cosmos Local Package Feed
Unable to find package XSharp. No packages exist with this id in source(s): Cosmos Local Package Feed
Unable to find package System.Reflection.TypeExtensions. No packages exist with this id in source(s): Cosmos Local Package Feed
@ Installing Cosmos.Core_Asm in SkippleOS finished (0.594 sec)
[Notification][Install] Install failed (project: SkippleOS, package: Cosmos.Core_Asm v0.1.0-localbuild)
Package restore failed. Rolling back package changes for 'SkippleOS'.
Unable to find package Cosmos.IL2CPU. No packages exist with this id in source(s): Cosmos Local Package Feed
Unable to find package XSharp. No packages exist with this id in source(s): Cosmos Local Package Feed
Unable to find package System.Reflection.TypeExtensions. No packages exist with this id in source(s): Cosmos Local Package Feed```

**Comment by zarlo** [comment]
you should not add Cosmos.core_asm to your project

**Comment by Kiirx** [comment]
oh, what sould I add?

**Comment by Kiirx** [comment]
e

**Pull request merged**
