### PR TITLE
Updated information across website and readme, moving links etc.

### PR DESCRIPTION
**Pull request by Arawn-Davies**
Moved links to their respective sections on the website, made new pages for Cosmos in the media, updated links and more

I've also made two new pages on the website [Cosmos in the media](http://www.gocosmos.org/inthemedia/) & [Cosmos resources](http://gocosmos.org/resources) and updated various pages such as [Cosmos News](http://www.gocosmos.org/news/) and [Cosmos Documentation](http://www.gocosmos.org/docs/) so the website is a better place to go to for more information and to learn more about Cosmos

### CODE REVIEW

**Comment by valentinbreiz** [comment]
Why delete all ?

**Comment by Arawn-Davies** [comment]
Kudzu asked for stuff to be moved over to the website, I guess it saves updating everything everywhere, we only have to update stuff on one thing :)

**Comment by Arawn-Davies** [comment]
ok, should i add a build status for the netcore branch in the netcore readme?

**Comment by jp2masa** [comment]
We just need the build status for the master branch. The netcore branch is just a feature branch.

**Comment by Arawn-Davies** [comment]
ok, plus at some point you'll be merging netcore into master so I see :) ready to be merged then I guess :P nothing I need to do? it seems to be a few commits behind the master but the only file changed is readme

**Comment by jp2masa** [comment]
It was already merged.

**Comment by Arawn-Davies** [comment]
oh ok, do i delete this fork now?

**Comment by jp2masa** [comment]
What fork?

**Pull request merged**
