### PR TITLE
Updates on int.ToString(`format`)

### PR DESCRIPTION
**Pull request by Guillermo-Santos**
Improved Hexadecimal format code as it was changing the value of the original variable (tested only on [SharpLab](https://sharplab.io/), since I did the change before testing on Cosmos, but I assume that if it was changing on normal C# context, then it should have been changing on Cosmos too), also added support for the decimal format and padding.

### CODE REVIEW

**Comment by Guillermo-Santos** [comment]
Code used to do the test:
``` csharp
using System;

var a = 255;
Console.WriteLine(ToString(ref a,"X"));
Console.WriteLine(a);
Console.WriteLine(ToString2(ref a,"X"));
Console.WriteLine(a);

/* Changed Version */
static string ToString(ref int aThis, string format)
{
    if (string.IsNullOrEmpty(format))
    {
        return "0";
    }

    string result = aThis > 0 ? string.Empty : "0";

    switch (format[0])
    {
        case 'X':
            int value = aThis;

            while (value != 0)
            {
                int remainder = value % 16;
                if (remainder < 10)
                {
                    result = remainder + result;
                }
                else
                {
                    char temp = (char)('A' + (remainder - 10));
                    result = temp + result;
                }
                
                value /= 16;
            }
            break;
        case 'D':
            result = aThis.ToString();
            break;
        default:
            return aThis.ToString();
    }

    if (format.Length > 1)
    {
        return int.TryParse(format.AsSpan(1), out int number) ? result.PadLeft(number, '0') : aThis.ToString();
    }
    else
    {
        return result;
    }
}

// Original
static string ToString2(ref int aThis, string format)
{
    if (format.Equals("X"))
    {
        string result = "";
        if(aThis == 0)
        {
            result = "0";
        }
        while (aThis != 0)
        {
            if (aThis % 16 < 10)
            {
                result = aThis % 16 + result;
            }
            else
            {
                string temp = "";
                switch (aThis % 16)
                {
                    case 10: temp = "A"; break;
                    case 11: temp = "B"; break;
                    case 12: temp = "C"; break;
                    case 13: temp = "D"; break;
                    case 14: temp = "E"; break;
                    case 15: temp = "F"; break;
                }
                result = temp + result;
            }
            aThis /= 16;
        }
        return result;
    }
    else
    {
        return aThis.ToString();
    }
}
```

**Comment by zarlo** [comment]
since this is been worked on right now 

could you make result in to a string builder so less strings are made

**Comment by Guillermo-Santos** [comment]
> since this is been worked on right now
> 
> could you make result in to a string builder so less strings are made

Done

**Comment by Guillermo-Santos** [comment]
What does this have to do with audio?

**Comment by quajak** [comment]
Seems like there was an issue building the iso. This might be a random error. Could you please add some test cases to Cosmos to ensure that the new version now handles the broken cases correctly?

**Comment by Guillermo-Santos** [comment]
> Seems like there was an issue building the iso. This might be a random error. Could you please add some test cases to Cosmos to ensure that the new version now handles the broken cases correctly?

Should I create a new project or do I add it to IO test?

**Comment by quajak** [comment]
Please add them to the existing Int32 tests in the BclSystem test kernel

**Comment by Guillermo-Santos** [comment]
Done

**Review by quajak — CHANGES_REQUESTED** [review]
Thanks for adding the test. Sorry for the miscommunication, we only need tests to ensure that the new version works :) not that the old one does not work

**Comment by Guillermo-Santos** [comment]
Done

**Review by quajak — APPROVED** [review]

**Pull request merged**
