### PR TITLE
Available VGA modes list in VS.

### PR DESCRIPTION
**Pull request by koteProgrammist**
Now you can see an available VGA video modes in Visual Studio.

### CODE REVIEW

**Review by quajak — DISMISSED** [review]
Thanks!

**Comment by koteProgrammist** [comment]
Why it not pass the test? I test in VS, all work normally

**Comment by clarence112** [comment]
You forgot to close the region on line 17

**Review by quajak — APPROVED** [review]

**Comment by koteProgrammist** [comment]
@quajak please merge

**Pull request merged**
