### PR TITLE
GPT Support

### PR DESCRIPTION
**Pull request by midonator1305**

### CODE REVIEW

**Comment by midonator1305** [comment]
It is not ready yet

**Comment by midonator1305** [comment]
Okay I found the issue. I had forgot to change the partition name to match that of the MBR disk and did not copy all the files. It works now no additional commits needed.

Since I'm not sure how to make a test for this considering it needs a seperate disk image [here](https://pastebin.com/RZYUt7Gy) is the output of the `Cosmos.Kernel.Tests.Fat.Kernel` test. 

Line 26 shows that it detected the GPT partition. (lines 21-25 won't show up they are just debug statements I didn't remove when testing)

**Comment by midonator1305** [comment]
It seems that all the files are unreadable outside of Cosmos

**Comment by Ray1015** [comment]
that's... not good

**Comment by midonator1305** [comment]
Yeah...

Trying to repair the filesystem in Linux doesn’t seem to work. It complains about not finding `.` and `..` directories in the folders and not being able to fix it

**Comment by midonator1305** [comment]
Well the GPT part functions so it’s ready to merge

**Pull request merged**
