### PR TITLE
VBE Driver work

### PR DESCRIPTION
**Pull request by zarlo**
Renamed VGAMemoryBlock to VBEMemoryBlock

### CODE REVIEW

**Comment by MyvarHD** [comment]
When i wrote the vbe driver, i did not think about the naming technically its a linear frame buffer, but vga stands for Video Graphic Array, witch is technically also correct, but vbe stands for VESA Bios Extension, VBEMemoryBlock is very wrong, VGAMemoryBlock is sort of correct but LinearFrameBuffer is the official name

**Comment by mihail-rotmg** [comment]
I only care about one thing.
Will it run faster?

**Comment by zarlo** [comment]
its not faster

**Comment by MyvarHD** [comment]
with a smart doublebuffer, and virtual box it runs at 30 fps

**Comment by mihail-rotmg** [comment]
How do i do that?

**Pull request closed without merging**
