### PR TITLE
Add French documentation and readme

### PR DESCRIPTION
**Pull request by Kiirx**

### CODE REVIEW

**Comment by Kiirx** [comment]
- [ ] Readme
- [ ] Documentation

**Comment by BlitzWolfMatthew** [comment]
Not saying your effort isn't appreciated, but why would we need readme files in multiple languages?

**Comment by Kiirx** [comment]
yes
Im doing the wiki rn

**Comment by quajak** [comment]
I appreciate the effort and will merge the results. My opinion on the matter is that maintaining documentation in multiple languages is a lot more work than just maintaining it in English. Given that the English version is in some parts out of date, I think it would be better to focus on improving and extending the English version.

**Comment by Arawn-Davies** [comment]
@valentinbreiz could you review this? sadly I don't speak French 🙃

**Comment by Kiirx** [comment]
Im also french it should be good but the help of valentinbreiz would be good yes

**Comment by Kiirx** [comment]
but why `Merge branch 'master' into master` (sorry im not a pro at git

**Comment by ptobuon** [comment]
I agree with quajak, i think we can add a google translator dropdown like in cosmos website: 
image
Full guide at: https://www.w3schools.com/howto/howto_google_translate.asp?msclkid=c13cce08d06b11eca4aed14f3c8a1317
can be add with this code:
```html
<div id="google_translate_element"></div>

<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
}
</script>```

**Comment by Kiirx** [comment]
> I agree with quajak, i think we can add a google translator dropdown like in cosmos website: image Full guide at: https://www.w3schools.com/howto/howto_google_translate.asp?msclkid=c13cce08d06b11eca4aed14f3c8a1317 can be add with this code:
> 
> ```
> <div id="google_translate_element"></div>
> 
> <script type="text/javascript">
> function googleTranslateElementInit() {
>   new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
> }
> </script>
> ```

I can't do that, I dont have the cosmos website's source code

**Comment by Kiirx** [comment]
@quajak if u have access to the website's code I'll let you do that

**Comment by ptobuon** [comment]
No, the website (https://goCosmos.org) has already Google Translate. We can add HTML in docs (https://cosmosos.github.io) to translate it.

**Pull request closed without merging**
