### PR TITLE
[WIP] Update Nasm Build version...

### PR DESCRIPTION
**Pull request by elkaamee326**
This build of NASM was confirmed (unofficially) that it resolved the error, by loading a large byte array in the Userkit. If you are currently using the User Kit, download the build of NASM to `C:\Users\YourUserName\.nuget\packages\cosmos.build\0.1.0-localbuild{YourUserKitVersionOfCosmos.Build}\tools\nasm\win`. It should also work with the dev kit as well. (Both builds should say the Cosmos.Build package version in your local directory).

Note: * replace `{YourUserKitVersionOfCosmos.Build}` with the nuget build version of Cosmos.Build...

The build was built from an open source 2012 version of NASM's source code. The cause of the error was `#define DEADMAN_LIMIT`. The evident solution was to increase the value and then rebuild NASM.

### CODE REVIEW

**Comment by elkaamee326** [comment]
Would there be anything else that is required to submit this pull request in a legitimate manner?

**Comment by charlesbetros** [comment]
Is this an official build of nasm? If so, what version and is there an official link to download it? I don't feel comfortable merging an executable if we don't know the contents or where the build came from.

**Comment by elkaamee326** [comment]
This was not an official Nasm build, but the source was official. Also, the source came from this site:  (I think the source was established in 2012 and earlier...) https://github.com/letolabs/nasm. 
(This is the exact repo, which was an old mirror of Nasm)... One question, is it not permitted to merge an unofficial build of Nasm? The source unfortunately didn’t have the prebuilt nasm executable. The only modification that was made to the source was in preproc.c line 334 #define DEADMAN_LIMIT (1 << 20). It was modified unofficially to a larger value to allow compilation of larger files. One thing to note: beware of loading massive executables, because VS might restart itself. Oh... There 2.10 rc15 is the source version. My apologies for any concerns, this is my first pull request. Let me know if there is anything further required.

**Comment by elkaamee326** [comment]
Instead of importing this unofficial build, I will erase this build from the pull request and research online to see and test if a modern Nasm official build will get rid of this error. Also, I will send the build link of the official build and the source code if needed. So, I will be changing this pull request to update Nasm version.

**Comment by elkaamee326** [comment]
Now, all that is left is testing...

**Comment by elkaamee326** [comment]
Also, this is where I downloaded the official build: https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/

**Comment by elkaamee326** [comment]
I will document the fasm and nasm build times and see if it resolves the interminable macro recursion error.

**Comment by elkaamee326** [comment]
If we use FASM, then we will have to change Cosmos.Build.Targets. I am not sure exactly how to make it work. When I tried to do it, it invoked fasm, but it then said FASM exited with the code 0. It was not an interminable macro recursion error, it is a Cosmos.Build.Tasks error. Some help with changing this would be apprectiated.

**Comment by quajak** [comment]
Thanks for looking into it. I must have misremebered since I thought we could just replace the NASM exe with FASM. Sorry about that.

**Comment by quajak** [comment]
It turns out I was thinking of yasm, not fasm. https://yasm.tortall.net/ Could you please compare the new nasm with yasm?

**Comment by elkaamee326** [comment]
Any assembler would work, as long as the command line params are the same for Nasm and as long as most things are similar, I will give it a shot. :)

**Comment by charlesbetros** [comment]
We can update our build targets if the arguments are different between assemblers. The important thing is to make sure we get all the features that nasm has.

**Comment by quajak** [comment]
Since yasm states `Yasm is a complete rewrite of the NASM assembler` that shouldnt be the problem. My main hope is to get the compile time further down while removing that limit on the length of inline arrays.

**Comment by elkaamee326** [comment]
I noticed one problem, `YASM` doesn't support `ELF` Compilation. It throws `yasm: FATAL: unrecognized object format 'ELF'` When I try to use bin instead it displays: `warning: binary object format does not support global variables` Idk why all these problems are occuring...

**Comment by elkaamee326** [comment]
Just to make sure that I am using the right args for yasm, what is the default nasm that is used without going into the Project Properties settings? This is necessary, to ensure the correct compilation using yasm.

**Comment by quajak** [comment]
The code for executing NASM is here `https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.Build.Tasks/Nasm.cs` `GenerateCommandLineCommands` sets all the command line arguments. I thought I had tried YASM once, where I just renamed it to nasm.exe and Cosmos was fine using it.

**Comment by elkaamee326** [comment]
Apparently, for the new version of Nasm, it didn't completely resolve the interminable macro recursion error. I will do a yasm test to confirm it resolves the error.

**Comment by quajak** [comment]
> Apparently, for the new version of Nasm, it didn't completely resolve the interminable macro recursion error. I will do a yasm test to confirm it resolves the error.

What does the new version do? Does it allow larger byte arrays or is there another limitation?

**Comment by elkaamee326** [comment]
No, it still solves the error but there is still a limitation. It definately was an enhancement to the build that we had before this update, but for incredibly large files, it throws the interminable macro recursion error. (A 22.3 mb) file was tested... Also, this new version compiles the code faster than the old version did.

**Comment by charlesbetros** [comment]
I think something to keep in mind is that a 22MB file should not be compiled in to the kernel.

**Comment by KM198912** [comment]
is there a link to the patch that fixes this in the source?

**Comment by elkaamee326** [comment]
I tried using Yasm, to test building a project and apparently only bin is supported. when I switched the Compile configuration to elf, the assembler reported these errors:
`1>bin\Debug\netcoreapp2.0\cosmos\CosmosKernel1.asm:3: error: instruction expected after label`
`1>bin\Debug\netcoreapp2.0\cosmos\CosmosKernel1.asm:4: error: unrecognized directive 'map'`

This was in the `#ifndef ELF_COMPILATION` statement

but when I set the configuration to bin, it just displayed a warning stating that:
`warning: binary object format does not support global variables`
Although, the compilation was still successfull and there were no errors. Also, the Yasm build time is sooooo much faster and it completely resolved the interminable macro recursion error! It took 1 min and 5 seconds to compile a project with massive assets! For the bin format, it works fine but in order for nasm to work with the elf format too, there is some work that must be done. Also, the modifications that were required to make this work was in Nasm.cs, I had to modify the OutputFormatEnum, because the assembler reported `ELF` and `Bin` don't exist in the current context, so I renamed the two enums params to elf and bin, which resolved one of the compilation errors. I also, had to remove the `xBuilder.AppendSwitch("-g");` because it created some problems with the compilation. I didn't really modify the nasm fields to yasm, instead I just imported yasm into the cosmos.build directory package and I renamed yasm to nasm. I don't really know how to do any other modifications with the targets and with the elf errors. This was definately a big enhancement from nasm to yasm though. :)

**Comment by elkaamee326** [comment]
@KM198912, the error wasn't completely resolved via `Nasm`. Although, `Yasm` fixed the error and it had a faster compile time. This  is the most modern source repo to the lastest version of `Nasm`. Yasm, although is basically a 'rewrite' of `Nasm` so the source should be very similar.

**Comment by elkaamee326** [comment]
I also think that `Yasm` compiles files at about 30 secs faster than `Nasm`...

**Comment by charlesbetros** [comment]
You compared by switching to bin on nasm too? I think we default to elf.

**Comment by elkaamee326** [comment]
Yeah, it is defaulted to `elf`, but when I attempted to compile with `elf`, it didn't work. When I used `bin` it worked and it compiled very efficiently.

**Comment by charlesbetros** [comment]
What I mean is. You compiled it as bin for both nasm and yasm and compared?

**Comment by elkaamee326** [comment]
No, for Nasm I attempted to compile it with `elf` and it didn't work because of the recursion error (I did not try with `bin` for Nasm). Besides, the extraction time usually only takes around 5 seconds to 20 seconds at most. Even though bin is faster, I believe that Yasm is faster by around 10 - 35 seconds at most. Also, it was the only assembler that resolved the recursive error with the minimum `params / args` modifications. I will try with Nasm `bin` and see if there is an updated time difference.

**Comment by quajak** [comment]
But `YASM` doesn't work with `ELF`?

**Comment by elkaamee326** [comment]
For some reason `YASM` doesn't work with `ELF`, when I attempted to compile with `YASM`, it displayed an error about map not existing in the current context and a syntax error there. For now, it only works with `Bin`. Also, I don't see the need for `elf` because when you do an `elf` compilation you still have to do a map extraction but with `.bin` on the other hand the compile times are much more efficient and faster.

Here are the `elf` (compilation) errors:
`1>bin\Debug\netcoreapp2.0\cosmos\CosmosKernel1.asm:3: error: instruction expected after label`
`1>bin\Debug\netcoreapp2.0\cosmos\CosmosKernel1.asm:4: error: unrecognized directive 'map'`

**Comment by elkaamee326** [comment]
Should I close this pull request, since `YASM` isn't compatible with elf? Or should we just stick with the new `Nasm` build?

**Comment by quajak** [comment]
I think we should keep this issue open and figure out how to get YASM working with elf, since it will be a big improvement if we can switch.

**Comment by charlesbetros** [comment]
The yasm docs list both bin and elf32/64 as output formats.

**Comment by elkaamee326** [comment]
I just figured out the cause of those two errors. I compiled a program as `elf` for the new `Nasm` and `Yasm` compared and for some reason, both of the assemblers don't support the `[Map]` directive. This is because the developers for the assemblers removed support for `elf` compilation with the `map` directive. Hence the error. Would this mean we would need to go into `IL2CPU.cs`? Or even modify `IL2CPU` so that it doesn't show this error. Do you recommend removing `elf` support and on project startup, should we set the build configuration to `.bin` by default? Personally, I don't know very much about `IL2CPU` and how we can change it to remove the `[map]` directive, but I know that it will require a lot of work.

**Comment by quajak** [comment]
Good find! Looking at the emitted asm file,
```
%ifndef ELF_COMPILATION
use32
org 0x1000000
[map all main.map]
%endif
```
does that mean our `%ifndef ELF_COMPILATION` check is incorrect? 
I assume that the correct fix would be to stop emitting the map directive when compiling for elf which most likely has to be done in IL2CPU. We are currently emitting the map directive at https://github.com/CosmosOS/IL2CPU/blob/master/source/Cosmos.IL2CPU/CosmosAssembler.cs#L549.

**Comment by elkaamee326** [comment]
No, its just that Elf doesn't support the map directive (as well as mapping) anymore because now only `.bin` supports it I believe. Also, in the new versions of Yasm and Nasm, they both don't support the org directive when compiling with elf. I think we should either remove that statement:
`%ifndef ELF_COMPILATION
use32
org 0x1000000
[map all main.map]
%endif` 
or, we can just remove all the of the `ELF_COMPILATION` statements.

**Comment by elkaamee326** [comment]
Okay, I got `elf` to work with Yasm and IL2CPU, but now it displays this when it tries to extract a map file (my build log):
```
1>------ Build started: Project: CosmosKernel1, Configuration: Debug Any CPU ------
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\Apps\Paint.cs(13,13,13,14): warning CS0108: 'Paint.x' hides inherited member 'App.x'. Use the new keyword if hiding was intended.
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\Apps\Paint.cs(13,16,13,17): warning CS0108: 'Paint.y' hides inherited member 'App.y'. Use the new keyword if hiding was intended.
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\Apps\Paint.cs(12,13,12,23): warning CS0649: Field 'Paint.PaintBrush' is never assigned to, and will always have its default value null
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\LogonUI\LoginManager.cs(22,28,22,37): warning CS0649: Field 'LoginManager.TextBox_X' is never assigned to, and will always have its default value 0
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\LogonUI\LoginManager.cs(22,39,22,48): warning CS0649: Field 'LoginManager.TextBox_Y' is never assigned to, and will always have its default value 0
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\LogonUI\LoginManager.cs(23,28,23,41): warning CS0169: The field 'LoginManager.LoginUIFont_X' is never used
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\LogonUI\LoginManager.cs(21,35,21,40): warning CS0169: The field 'LoginManager.LogoY' is never used
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\Dock\Dock.cs(20,14,20,16): warning CS0169: The field 'Dock.AM' is never used
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\Dock\Dock.cs(20,18,20,20): warning CS0169: The field 'Dock.PM' is never used
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\Apps\Windows\Controls\Textbox.cs(113,22,113,29): warning CS0649: Field 'Textbox.cLength' is never assigned to, and will always have its default value 0
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\LogonUI\LoginManager.cs(21,28,21,33): warning CS0169: The field 'LoginManager.LogoX' is never used
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\LogonUI\LoginManager.cs(23,43,23,56): warning CS0169: The field 'LoginManager.LoginUIFont_Y' is never used
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\Apps\Windows\Controls\Textbox.cs(12,18,12,26): warning CS0169: The field 'Textbox.keyEvent' is never used
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\Image Support\Bitmap\Bitmap.cs(16,18,16,27): warning CS0169: The field 'Bitmap.mDebugger' is never used
1>C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\GUI\Apps\Windows\App.cs(37,14,37,21): warning CS0414: The field 'App.hovered' is assigned but its value is never used
1>CosmosKernel1 -> C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\bin\Debug\netcoreapp2.0\cosmos\CosmosKernel1.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\elkaa\Documents\CosmosKernel1\CosmosKernel1\bin\Debug\netcoreapp2.0\cosmos\CosmosKernel1.dll
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.LOCAL_ARGUMENT_INFO'
1>IL2CPU task took 00:01:22.7998446
1>Nasm task took 00:01:31.2390425           
                        //-------  (manually added) This is a pretty big project. On a smaller project it compiled in only 5secs... ------ ////
1>-Ttext 0x2000000 -Tdata 0x1000000 -e Kernel_Start -o bin\Debug\netcoreapp2.0\cosmos\CosmosKernel1.bin bin\Debug\netcoreapp2.0\cosmos\CosmosKernel1.obj
1>LD task took 00:00:01.6896300
1>Extracting Map file...
1>Extracting Map file took 00:00:28.4942017
1>C:\Users\elkaa\.nuget\packages\cosmos.build\0.1.0-localbuild20210416035217\build\Cosmos.Build.targets(258,9): error MSB4018: The "ExtractMapFromElfFile" task failed unexpectedly.
1>C:\Users\elkaa\.nuget\packages\cosmos.build\0.1.0-localbuild20210416035217\build\Cosmos.Build.targets(258,9): error MSB4018: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Labels.Name'.
1>C:\Users\elkaa\.nuget\packages\cosmos.build\0.1.0-localbuild20210416035217\build\Cosmos.Build.targets(258,9): error MSB4018:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
1>C:\Users\elkaa\.nuget\packages\cosmos.build\0.1.0-localbuild20210416035217\build\Cosmos.Build.targets(258,9): error MSB4018:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
1>C:\Users\elkaa\.nuget\packages\cosmos.build\0.1.0-localbuild20210416035217\build\Cosmos.Build.targets(258,9): error MSB4018:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
1>C:\Users\elkaa\.nuget\packages\cosmos.build\0.1.0-localbuild20210416035217\build\Cosmos.Build.targets(258,9): error MSB4018:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
1>C:\Users\elkaa\.nuget\packages\cosmos.build\0.1.0-localbuild20210416035217\build\Cosmos.Build.targets(258,9): error MSB4018:    at IL2CPU.Debug.Symbols.SQL.Exec(String aSql) in C:\Users\elkaa\Desktop\Source\IL2CPU\source\IL2CPU.Debug.Symbols\SQL.cs:line 27
1>C:\Users\elkaa\.nuget\packages\cosmos.build\0.1.0-localbuild20210416035217\build\Cosmos.Build.targets(258,9): error MSB4018:    at IL2CPU.Debug.Symbols.SQL.MakeIndex(String aTable, String aCol, Boolean aUnique) in C:\Users\elkaa\Desktop\Source\IL2CPU\source\IL2CPU.Debug.Symbols\SQL.cs:line 49
1>C:\Users\elkaa\.nuget\packages\cosmos.build\0.1.0-localbuild20210416035217\build\Cosmos.Build.targets(258,9): error MSB4018:    at IL2CPU.Debug.Symbols.DebugInfo.CreateIndexes() in C:\Users\elkaa\Desktop\Source\IL2CPU\source\IL2CPU.Debug.Symbols\DebugInfo.cs:line 113
1>C:\Users\elkaa\.nuget\packages\cosmos.build\0.1.0-localbuild20210416035217\build\Cosmos.Build.targets(258,9): error MSB4018:    at IL2CPU.Debug.Symbols.ObjDump.ExtractMapSymbolsForElfFile(String debugFile, String mapFile) in C:\Users\elkaa\Desktop\Source\IL2CPU\source\IL2CPU.Debug.Symbols\ObjDump.cs:line 131
1>C:\Users\elkaa\.nuget\packages\cosmos.build\0.1.0-localbuild20210416035217\build\Cosmos.Build.targets(258,9): error MSB4018:    at Cosmos.Build.Tasks.ExtractMapFromElfFile.Execute() in C:\Users\elkaa\Desktop\Source\Cosmos\source\Cosmos.Build.Tasks\ExtractMapFromElfFile.cs:line 79
1>C:\Users\elkaa\.nuget\packages\cosmos.build\0.1.0-localbuild20210416035217\build\Cosmos.Build.targets(258,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Users\elkaa\.nuget\packages\cosmos.build\0.1.0-localbuild20210416035217\build\Cosmos.Build.targets(258,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>Done building project "CosmosKernel1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

As you can see, it displays this error when we try to extract a map file. Elf doesn't support map files for some reason. So, should we remove the `ExtractFromMapElf`? Also, what is the need for extracting map files in Cosmos? If we should remove it, where is it located and how would I remove it properly? This is the only thing that is stopping us from successfully compiling an OS in an `elf` format. Should we remove the ability to extract map files? Or is it necessary, in order for us to successfully create an ISO image?

**Comment by elkaamee326** [comment]
Okay, I fixed the error. Finally, Yasm supports `elf`!

**Comment by charlesbetros** [comment]
There is still a map file for with address/method names?

Does bin also still work?

Debugging is working in visual studio? (ie. Breakpoints)

**Comment by elkaamee326** [comment]
For some reason, `.bin` doesn't work and it is corrupt. It only compiles with elf. This was caused from some problems with IL2CPU. I will close this pull request because it was very difficult to get this to work and it was very tedious. Also, trying to make this work was extremely difficult.

**Comment by quajak** [comment]
Thank you for all your work on this issue. Due to how much there is to gain from switching to yasm, I would like to keep this pr open, even if you are no longer interested in working on it, which is understandable. If I have time, I will take a look and see if I can figure out what is needed to get .bin running.

**Comment by charlesbetros** [comment]
I tried nasm and yasm side by side like this:
```
nasm.exe -g null -f bin -DBIN_COMPILATION -O0 Kernel_bin.asm
nasm.exe -g dwarf2 -f elf -DELF_COMPILATION -O0 Kernel_elf.asm

yasm.exe -g null -f bin -DBIN_COMPILATION -O0 Kernel_bin.asm
yasm.exe -g dwarf2 -f elf -DELF_COMPILATION -O0 Kernel_elf.asm
```

I got a single warning about globals not supported using bin format, but I didn't have to change anything in the asm. The output and map file were created with no issues.

**Comment by elkaamee326** [comment]
Did you make any modifications to IL2CPU or Cosmos itself? Because, when I tried to make it work my Cosmos it just corrupted it somehow by displaying a bunch of warnings and I don't know why. Like those `.bin` warnings...

**Comment by charlesbetros** [comment]
I didn't make any changes except to call yasm instead of nasm.

**Comment by MishaTY** [comment]
Not needed anymore because of #1993

**Comment by valentinbreiz** [comment]
Now works using multiboot2, no more invalid multiboot image

**Review by MishaTY — DISMISSED** [review]

**Review by MishaTY — APPROVED** [review]

**Pull request merged**
