### PR TITLE
Visual Studio 2022 Support for Cosmos

### PR DESCRIPTION
**Pull request by valentinbreiz**
Todo: 
- [x] Build support
- [x] Create a new Cosmos project
- [x] Debugging support
- [ ] Cosmos Icon in project root tree /!\ Temporary icon
- [x] Rewrite Property Pages
- [x] Fully Integrate QEMU into Property Pages
- [x] Fix .NET 4.8 / 5.0 issue
- [x] Fix NRE when CompileVBEMultiboot not set in csproj

### CODE REVIEW

**Comment by KM198912** [comment]
Currently on hold until Microsoft introduces the possibility to use Custom Property Pages.

**Comment by valentinbreiz** [comment]
@KM198912 @quajak this error keeps happening somewhen... this should need to be fixed

image

**Comment by KM198912** [comment]
@valentinbreiz yes, this is the todo I added, debug symbols gers confused between 4.8 and 5.0, it uses 5.0 when it is supposed to use 4.8

**Comment by KM198912** [comment]
https://github.com/CosmosOS/IL2CPU/commit/aceeab74d6039f9ddc238097e9b9aee81822f915was supposed to fix that

**Comment by Arawn-Davies** [comment]
image
When running install-vs2022.bat, it results in incorrect usage of cswinrt, as WinRT has been discontinued from .NET 5.0
image

**Comment by valentinbreiz** [comment]
It's not a bug in the VS2022 branch, it's also in master

**Comment by Arawn-Davies** [comment]
> It's not a bug in the VS2022 branch, it's also in master

ah okay, maybe with the cross-platform PR we can work on a better cross platform gui with .NET MAUI or similar, something that doesn't rely on winrt so much :)

**Comment by quajak** [comment]
Inno setup uses WinRT. We would at least have to rewrite this part https://github.com/CosmosOS/Cosmos/blob/master/Setup/Cosmos.iss#L159-L230

**Comment by Kiirx** [comment]
Microsoft dropped support for visual studio 2019 
https://devblogs.microsoft.com/visualstudio/support-ends-for-older-versions-of-visual-studio-feb2022/

**Review by MishaTY — APPROVED** [review]

**Pull request merged**
