### PR TITLE
CGS Update (part 1)

### PR DESCRIPTION
**Pull request by SzymekkYT**
All changes
-Fixed VBE positioning bug issue #3009 
-SVGAII & VBE - The bug with things going off screen has been fixed
obraz_2024-05-10_231225365
-SVGAII - Fixed draw filled rectangles going also off screen. it was already fixed in vbe.
Warning: fixing off screen left side will be added in part 2 unless someone wants to do it first ;p

### CODE REVIEW

**Comment by aomine001** [comment]
Nice code

**Review by aomine001 — APPROVED** [review]
Now it makes more sense

**Comment by PratyushKing** [comment]
add a bool or smth to do this, dont do it directly, approved ig 👍🏻

**Comment by SzymekkYT** [comment]
done!@

**Comment by SzymekkYT** [comment]
Okay, its ready!

**Review by valentinbreiz — APPROVED** [review]

**Comment by valentinbreiz** [comment]
Thanks for the contribution :)

**Comment by 9xbt** [comment]
> add a bool or smth to do this, dont do it directly, approved ig 👍🏻

why may i ask?

**Pull request merged**
