### PR TITLE
Update ACPI.cs

### PR DESCRIPTION
**Pull request by Epiczhul**

### CODE REVIEW

**Comment by Epiczhul** [comment]
DONT MERGE!!!!!! I EXCEDENTLY REMOVE SOMETHING FROM ACPI!!!!!!!!!!!!!!!

**Review by 9xbt — COMMENTED** [review]
holy shit this is cancerous

**Comment by 9xbt** [comment]
@zarlo please close this shit. bro removed all of ACPI code making this even harder https://github.com/CosmosOS/Cosmos/issues/2503

**Comment by Epiczhul** [comment]
I put the code back where it belong! @9xbt

**Comment by GoldenretriverYT** [comment]
changed a total of one line. LGTM. should be merged imo

**Comment by Winksplorer** [comment]
lgtm

**Comment by Kiirx** [comment]
what the hell.

**Comment by zarlo** [comment]
> what the hell.

its only a white space change

**Pull request closed without merging**
