### PR TITLE
Guid Implementation

### PR DESCRIPTION
**Pull request by MishaTY**
Same as: #942

### CODE REVIEW

**Comment by zarlo** [comment]
xD is this still not in it was started in 2017

**Comment by zarlo** [comment]
and it looks like it still have te same issues with the guids been the same in the tests

**Comment by quajak** [comment]
I think thats a problem with how we seed the random number generators currently. Making the random static should fix the issue.

**Comment by zarlo** [comment]
mmm that a bit more of a hack then a fix

**Comment by quajak** [comment]
Yeah, the correct fix would be to improve the seeding of the random number generator.

**Comment by quajak** [comment]
@MishaTY The issue is that https://github.com/CosmosOS/Cosmos/blob/a1c4011cbfadcec5a8b61fac56d1d1a4de739462/source/Cosmos.System2_Plugs/System/RandomImpl.cs#L30-L33 does not use `GenerateGlobalSeed`.

**Review by quajak — APPROVED** [review]

**Pull request merged**
