### PR TITLE
List all requirements 1-by-1

### PR DESCRIPTION
**Pull request by sgetaz**
Add all prerequisite "exceptions" to a list, and show upon BuildStatus.MissingPrerequisites

### CODE REVIEW

**Comment by sgetaz** [comment]
Please review

**Comment by mterwoord** [comment]
Seems to work OK, but in the end, the builder says Error, but no errors occurred.

**Comment by sgetaz** [comment]
Hi,

I am away this weekend, but I will have a lool when I get back.



-----Original Message-----

**Comment by sgetaz** [comment]
I fixed the error, now I must learn some more Github intricacies to add this change to the pull-request...

**Pull request merged**
