### PR TITLE
Extended ASCII characters.

### PR DESCRIPTION
**Pull request by valentinbreiz**
I think this is a bad way to do it, but it works ... What do you think @fanoI ?

### CODE REVIEW

**Comment by zarlo** [comment]
dont we use unicode

**Comment by fanoI** [comment]
C# String are Unicode (UTF-16) yes but the terminal in text mode is limited to the legacy 8 bit code pages so we need to Encode / Decode the text for the terminal.

**Comment by czhower** [comment]
How can I see the changes? I opened it in git desktop but it shows nothing different in that branch. What are the basic changes?

Yes eventually full Unicode is the goal, but its a LOT of work. Extended ASCII gets us Western European with only little work and serves as a good mid term solution.

**Comment by czhower** [comment]
Changes look fine to me for now.

**Comment by czhower** [comment]
Merged

**Comment by czhower** [comment]
A suggestion - an array with lookups would be shorter code and also faster. A byte array of 255 elements.

**Comment by czhower** [comment]
Actually ignore that - as the incoming values are Unicode, it would make the array very large if the code points are scattered.

**Pull request merged**
