### PR TITLE
DHCP Fix

### PR DESCRIPTION
**Pull request by valentinbreiz**

### CODE REVIEW

**Review by poggingfish — APPROVED** [review]
Looks fine to me.

**Review by MishaTY — APPROVED** [review]

**Review by MishaTY — APPROVED** [review]

**Comment by quajak** [comment]
Are you saying this is no longer required?

**Comment by Kiirx** [comment]
> Are you saying this is no longer required?

Yes

**Comment by Kiirx** [comment]
ahem

**Comment by quajak** [comment]
@valentinbreiz Can this be merged?

**Comment by valentinbreiz** [comment]
No

**Comment by valentinbreiz** [comment]
It brokes the working implementation but it's a better way to use DHCP
It just needs a few fixes

**Comment by valentinbreiz** [comment]
Implemented in https://github.com/CosmosOS/Cosmos/pull/2808

**Pull request closed without merging**
