### PR TITLE
Combine QEMU power functions with standard functions

### PR DESCRIPTION
**Pull request by RaphMar2021**
Combine the QEMU power functions ( QemuShutdown() and QemuReboot() ) with standard power functions ( Shutdown(), Reboot() )

### CODE REVIEW

**Comment by terminal-cs** [comment]
Not a great idea to brute force it because this could invoke some unwanted function in a device on the system

**Comment by RaphMar2021** [comment]
wdym?

**Comment by quajak** [comment]
is there anyway to detect if we are running in qemu?

**Comment by zarlo** [comment]
from memory there are CPU flags we can check (this is still not 100%)

**Comment by zarlo** [comment]
yep the CPU vendor id should be "TCGTCGTCGTCG"

**Comment by quajak** [comment]
Then we should either let the user do the check, or do it in the method.

**Comment by terminal-cs** [comment]
the pr was merged and this no longer is needed, you can delete it

**Comment by RaphMar2021** [comment]
bruhhhhhhhhhhhhhhhhhhhh

**Pull request closed without merging**
