### PR TITLE
expose a way to register your own filesystem

### PR DESCRIPTION
**Pull request by zarlo**

### CODE REVIEW

**Comment by terminal-cs** [comment]
Will documentation on how to use this be written?

**Comment by zarlo** [comment]
not by me

**Comment by AsertCreator** [comment]
formating? that would be cool

**Comment by zarlo** [comment]
that will not be added in this

**Review by quajak — APPROVED** [review]

**Comment by zarlo** [comment]
@quajak merge in when ever you want

**Comment by AsertCreator** [comment]
will it'll get merged?

**Pull request merged**
