### PR TITLE
Add paging support

### PR DESCRIPTION
**Pull request by MishaTy**
Very WIP - will not work yet

### CODE REVIEW

**Comment by Kiirx** [comment]
if it doesnt work yet you should put it as a draft

**Comment by ascpixi** [comment]
I'm not sure if this is still active, but looking at the code, this will not work, since in its current state, it's using PDPTs, while nowhere the `CR4.PAE` bit is set.

**Comment by MishaProductions** [comment]
Closing this PR as the correct place to implement this is in IL2CPU

**Comment by MishaTy** [comment]
will make a new PR

**Pull request closed without merging**
